// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1) {
  return window['go']['main']['App']['AddProvider'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetBrowserAgent() {
  return window['go']['main']['App']['GetBrowserAgent']();
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProviderPresets() {
  return window['go']['main']['App']['GetProviderPresets']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ListWorkspaceFiles(arg1) {
  return window['go']['main']['App']['ListWorkspaceFiles'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ReadTerminal(arg1) {
  return window['go']['main']['App']['ReadTerminal'](arg1);
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1);
}

export function ReadWorkspaceFolder(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceFolder'](arg1, arg2);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetBrowserAgent(arg1) {
  return window['go']['main']['App']['SetBrowserAgent'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function StopBrowserAgent() {
  return window['go']['main']['App']['StopBrowserAgent']();
}

export function UpdateProvider(arg1) {
  return window['go']['main']['App']['UpdateProvider'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
