// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {db} from '../models';
import {main} from '../models';
import {core} from '../models';

export function AddProvider(arg1:llm.ProviderConfig):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<db.Session>;

export function CreateTerminal(arg1:string,arg2:string):Promise<main.TerminalInfo>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetBrowserAgent():Promise<core.BrowserAgent>;

export function GetCurrentModel():Promise<string>;

export function GetModels():Promise<Array<llm.ModelConfig>>;

export function GetProviderPresets():Promise<Array<llm.ProviderPreset>>;

export function GetProviders():Promise<Array<llm.ProviderConfig>>;

export function GetServerPort():Promise<string>;

export function GetSessionMessages(arg1:string):Promise<Array<db.Message>>;

export function GetSessions(arg1:string):Promise<Array<db.Session>>;

export function GetWorkspace():Promise<string>;

export function ListTerminals():Promise<Array<string>>;

export function ListWorkspaceFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function PickDirectory():Promise<string>;

export function ReadTerminal(arg1:string):Promise<string>;

export function ReadWorkspaceFile(arg1:string):Promise<string>;

export function ReadWorkspaceFolder(arg1:string,arg2:number):Promise<Array<main.FolderContent>>;

export function RemoveProvider(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetBrowserAgent(arg1:core.BrowserAgent):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function StopBrowserAgent():Promise<void>;

export function UpdateProvider(arg1:llm.ProviderConfig):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
