// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {core} from '../models';
import {llm} from '../models';

export function CreateSession(arg1:string):Promise<db.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetBrowserAgent():Promise<core.BrowserAgent>;

export function GetCurrentModel():Promise<string>;

export function GetModels():Promise<Array<llm.ModelConfig>>;

export function GetServerPort():Promise<string>;

export function GetSessionMessages(arg1:string):Promise<Array<db.Message>>;

export function GetSessions(arg1:string):Promise<Array<db.Session>>;

export function GetWorkspace():Promise<string>;

export function PickDirectory():Promise<string>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SetBrowserAgent(arg1:core.BrowserAgent):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function StopBrowserAgent():Promise<void>;
