// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetBrowserAgent() {
  return window['go']['main']['App']['GetBrowserAgent']();
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SetBrowserAgent(arg1) {
  return window['go']['main']['App']['SetBrowserAgent'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function StopBrowserAgent() {
  return window['go']['main']['App']['StopBrowserAgent']();
}
